services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  mysql:
    env_file:
      - ./server/.env
    image: mariadb:10.11
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  server:
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume to prevent local node_modules from overwriting container's
    depends_on:
      - mysql
      - mongodb
    restart: unless-stopped

  client:
    env_file:
      - ./client/.env.development
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongodb_data:
  mysql_data:
